export const ADD_ACTION = 'ADD_ACTION';
export const TOGGLE_ACTION = 'TOGGLE_ACTION';
export const TOGGLE_ALL_ACTIONS = 'TOGGLE_ALL_ACTIONS';
export const EDIT_ACTION = 'EDIT_ACTION';
export const DELETE_ACTION = 'DELETE_ACTION';
export const DELETE_ALL_ACTIONS = 'DELETE_ALL_ACTIONS';


export const EDIT_SOURCE = 'EDIT_SOURCE';
export const EDIT_RESULT = 'EDIT_RESULT';
export const UPDATE_LINE_COUNTERS = 'UPDATE_LINE_COUNTERS';
